apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
          - name: JVM_OPTS
            value: "-Xms32M -Xmx128M"
          - name: KAFKA_BROKERCONNECT
            value: "kafka-cluster-kafka-bootstrap:9092"
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 600m
              memory: 500Mi
      nodeSelector:
        nodeTypeClass: {{ .Values.nodeSelector.nodeTypeClass }}      